# Generated by Django 5.0.6 on 2024-06-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('season', models.IntegerField()),
                ('neutral', models.BooleanField()),
                ('playoff', models.BooleanField()),
                ('team1', models.CharField(max_length=50)),
                ('team2', models.CharField(max_length=50)),
                ('elo1_pre', models.FloatField()),
                ('elo2_pre', models.FloatField()),
                ('elo_prob1', models.FloatField()),
                ('elo_prob2', models.FloatField()),
                ('elo1_post', models.FloatField()),
                ('elo2_post', models.FloatField()),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('is_home', models.BooleanField()),
                ('is_win', models.BooleanField()),
                ('gm_no', models.IntegerField()),
            ],
        ),
    ]
