# Generated by Django 5.0.6 on 2024-06-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0002_historicaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFLTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
                ('color_hex', models.CharField(max_length=50)),
            ],
        ),
    ]
