# Generated by Django 5.0.6 on 2024-06-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0003_nflteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflteam',
            name='historical_games',
            field=models.ManyToManyField(blank=True, related_name='teams', to='app_template.historicaldata'),
        ),
        migrations.AlterField(
            model_name='nflteam',
            name='abbreviation',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='nflteam',
            name='color_hex',
            field=models.CharField(max_length=7),
        ),
    ]
