# Generated by Django 5.0.6 on 2024-06-30 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0004_nflteam_historical_games_alter_nflteam_abbreviation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarterbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('QBR', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Projection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
                ('mean', models.FloatField()),
                ('median', models.FloatField()),
                ('madePlayoffs', models.IntegerField()),
                ('wonDivision', models.IntegerField()),
                ('wonConference', models.IntegerField()),
                ('wonSuperBowl', models.IntegerField()),
                ('stdv', models.FloatField()),
                ('ptdiff', models.FloatField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_template.nflteam')),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('season', models.IntegerField()),
                ('week', models.IntegerField()),
                ('after_bye_home', models.BooleanField()),
                ('after_bye_away', models.BooleanField()),
                ('city', models.CharField(max_length=100)),
                ('isNeutral', models.BooleanField()),
                ('isComplete', models.BooleanField()),
                ('homeScore', models.IntegerField()),
                ('awayScore', models.IntegerField()),
                ('awayTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_teams', to='app_template.nflteam')),
                ('homeTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_teams', to='app_template.nflteam')),
            ],
        ),
    ]
