# Generated by Django 5.0.6 on 2024-07-01 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0005_quarterbacks_projection_upcominggames'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflteam',
            name='confWins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nflteam',
            name='divWins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nflteam',
            name='elo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nflteam',
            name='totWins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projection',
            name='currWeek',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField()),
                ('playoffRound', models.CharField(max_length=50)),
                ('seeding', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_template.nflteam')),
            ],
        ),
        migrations.AddField(
            model_name='projection',
            name='seasons',
            field=models.ManyToManyField(related_name='projections', to='app_template.season'),
        ),
    ]
