# Generated by Django 5.0.6 on 2024-07-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0006_nflteam_confwins_nflteam_divwins_nflteam_elo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('long', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
    ]
