# Generated by Django 5.0.6 on 2024-07-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0007_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflteam',
            name='team_city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
