# Generated by Django 5.0.6 on 2024-07-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0008_nflteam_team_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nflteam',
            old_name='team_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='nflteam',
            old_name='team_name',
            new_name='name',
        ),
    ]
