# Generated by Django 5.0.6 on 2024-07-08 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0009_rename_team_city_nflteam_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QBStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('passing_yards', models.IntegerField()),
                ('touchdowns', models.IntegerField()),
                ('interceptions', models.IntegerField()),
                ('rating', models.FloatField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_template.nflteam')),
            ],
        ),
    ]
