# Generated by Django 5.0.6 on 2024-07-08 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0010_qbstats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QBStats',
        ),
    ]
