# Generated by Django 5.0.6 on 2024-07-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0011_delete_qbstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projection',
            name='ptdiff',
        ),
        migrations.RemoveField(
            model_name='projection',
            name='seasons',
        ),
    ]
