# Generated by Django 5.0.6 on 2024-07-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0012_remove_projection_ptdiff_remove_projection_seasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='projection',
            name='_25',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projection',
            name='_75',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
