# Generated by Django 5.0.6 on 2024-07-10 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0013_projection__25_projection__75'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projection',
            old_name='_25',
            new_name='firstquartile',
        ),
        migrations.RenameField(
            model_name='projection',
            old_name='_75',
            new_name='thirdquartile',
        ),
    ]
