# Generated by Django 5.0.6 on 2024-07-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0014_rename__25_projection_firstquartile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projection',
            name='playoffPercent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
