# Generated by Django 5.0.6 on 2024-07-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0015_projection_playoffpercent'),
    ]

    operations = [
        migrations.AddField(
            model_name='projection',
            name='divisionPercent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
