# Generated by Django 5.0.6 on 2024-07-14 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0017_remove_projection_divisionpercent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='upcominggames',
            name='user',
        ),
    ]
