# Generated by Django 5.0.6 on 2024-07-14 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0019_projection_user_upcominggames_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcominggames',
            name='teamPicked',
            field=models.ForeignKey(default=113, on_delete=django.db.models.deletion.CASCADE, to='app_template.nflteam'),
            preserve_default=False,
        ),
    ]
