# Generated by Django 5.0.6 on 2024-07-15 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0021_remove_historicaldata_gm_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcominggames',
            name='isCustom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upcominggames',
            name='isPicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upcominggames',
            name='teamPicked',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_template.nflteam'),
        ),
    ]
