# Generated by Django 5.0.6 on 2024-07-15 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0022_upcominggames_iscustom_upcominggames_ispicked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcominggames',
            name='isCustom',
        ),
        migrations.RemoveField(
            model_name='upcominggames',
            name='isPicked',
        ),
        migrations.RemoveField(
            model_name='upcominggames',
            name='teamPicked',
        ),
    ]
