# Generated by Django 5.0.6 on 2024-07-15 17:44

import django.db.models.deletion
import django.db.models.query
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0026_upcominggames_iscustom_upcominggames_ispicked_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcominggames',
            name='teamPicked',
            field=models.ForeignKey(default=145, on_delete=django.db.models.deletion.CASCADE, to='app_template.nflteam'),
        ),
        migrations.AlterField(
            model_name='upcominggames',
            name='user',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
