# Generated by Django 5.0.6 on 2024-07-15 17:57

import app_template.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_template', '0031_remove_upcominggames_iscustom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='upcominggames',
            name='isCustom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upcominggames',
            name='isPicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upcominggames',
            name='teamPicked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_template.nflteam'),
        ),
        migrations.AddField(
            model_name='upcominggames',
            name='user',
            field=models.ForeignKey(default=app_template.models.get_default_user_id, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
