# Generated by Django 5.0.6 on 2024-07-15 19:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('long', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('season', models.PositiveIntegerField()),
                ('neutral', models.BooleanField()),
                ('playoff', models.CharField(blank=True, max_length=1, null=True)),
                ('team1', models.CharField(max_length=50)),
                ('team2', models.CharField(max_length=50)),
                ('elo1_pre', models.FloatField(default=0.0)),
                ('elo2_pre', models.FloatField(default=0.0)),
                ('elo_prob1', models.FloatField(default=0.0)),
                ('elo_prob2', models.FloatField(default=0.0)),
                ('elo1_post', models.FloatField(default=0.0)),
                ('elo2_post', models.FloatField(default=0.0)),
                ('qbelo1_pre', models.FloatField(default=0.0)),
                ('qbelo2_pre', models.FloatField(default=0.0)),
                ('qb1', models.CharField(default='', max_length=50)),
                ('qb2', models.CharField(default='', max_length=50)),
                ('qb1_value_pre', models.FloatField(default=0.0)),
                ('qb2_value_pre', models.FloatField(default=0.0)),
                ('qb1_adj', models.FloatField(default=0.0)),
                ('qb2_adj', models.FloatField(default=0.0)),
                ('qbelo_prob1', models.FloatField(default=0.0)),
                ('qbelo_prob2', models.FloatField(default=0.0)),
                ('qb1_game_value', models.FloatField(default=0.0)),
                ('qb2_game_value', models.FloatField(default=0.0)),
                ('qb1_value_post', models.FloatField(default=0.0)),
                ('qb2_value_post', models.FloatField(default=0.0)),
                ('qbelo1_post', models.FloatField(default=0.0)),
                ('qbelo2_post', models.FloatField(default=0.0)),
                ('score1', models.IntegerField(default=0)),
                ('score2', models.IntegerField(default=0)),
                ('quality', models.FloatField(default=0.0)),
                ('importance', models.FloatField(default=0.0)),
                ('total_rating', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Quarterbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('QBR', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NFLTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('abbreviation', models.CharField(max_length=3, unique=True)),
                ('color_hex', models.CharField(max_length=7)),
                ('totWins', models.IntegerField(default=0)),
                ('divWins', models.IntegerField(default=0)),
                ('confWins', models.IntegerField(default=0)),
                ('elo', models.FloatField(default=0.0)),
                ('historical_games', models.ManyToManyField(blank=True, related_name='teams', to='main.historicaldata')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
                ('mean', models.FloatField()),
                ('median', models.FloatField()),
                ('madePlayoffs', models.IntegerField()),
                ('wonDivision', models.IntegerField()),
                ('wonConference', models.IntegerField()),
                ('wonSuperBowl', models.IntegerField()),
                ('stdv', models.FloatField()),
                ('firstquartile', models.FloatField()),
                ('thirdquartile', models.FloatField()),
                ('currWeek', models.IntegerField(default=0)),
                ('isCustom', models.BooleanField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nflteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField()),
                ('playoffRound', models.CharField(max_length=50)),
                ('seeding', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nflteam')),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('season', models.IntegerField()),
                ('week', models.IntegerField()),
                ('after_bye_home', models.BooleanField()),
                ('after_bye_away', models.BooleanField()),
                ('city', models.CharField(max_length=100)),
                ('isNeutral', models.BooleanField()),
                ('isComplete', models.BooleanField()),
                ('homeScore', models.IntegerField()),
                ('awayScore', models.IntegerField()),
                ('isCustom', models.BooleanField(blank=True, default=False, null=True)),
                ('isPicked', models.BooleanField(blank=True, default=False, null=True)),
                ('awayTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_teams', to='main.nflteam')),
                ('homeTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_teams', to='main.nflteam')),
                ('teamPicked', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.nflteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
