# Generated by Django 5.0.6 on 2024-07-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_upcominggames_iscustom_upcominggames_ispicked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflteam',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logo/'),
        ),
    ]
