# Generated by Django 5.0.6 on 2024-07-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_nflteam_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nflteam',
            name='logo',
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='score1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='score2',
            field=models.FloatField(default=0),
        ),
    ]
