# Generated by Django 3.2.6 on 2024-07-16 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20240716_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nflteam',
            old_name='conference_wins',
            new_name='conf_wins',
        ),
        migrations.RenameField(
            model_name='nflteam',
            old_name='division_wins',
            new_name='div_wins',
        ),
        migrations.RenameField(
            model_name='nflteam',
            old_name='total_wins',
            new_name='tot_wins',
        ),
    ]
