# Generated by Django 3.2.6 on 2024-07-30 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20240716_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcominggames',
            name='is_custom',
        ),
        migrations.RemoveField(
            model_name='upcominggames',
            name='is_picked',
        ),
        migrations.RemoveField(
            model_name='upcominggames',
            name='team_picked',
        ),
        migrations.RemoveField(
            model_name='upcominggames',
            name='user',
        ),
        migrations.CreateModel(
            name='GamePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('', 'No Prediction')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.upcominggames')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='upcominggames',
            name='user_predictions',
            field=models.ManyToManyField(through='main.GamePrediction', to=settings.AUTH_USER_MODEL),
        ),
    ]
