# Generated by Django 3.2.6 on 2024-07-30 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_auto_20240729_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarterbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('QBR', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='gameprediction',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gameprediction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Quarterback',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='longitude',
            new_name='long',
        ),
        migrations.RenameField(
            model_name='nflteam',
            old_name='conf_wins',
            new_name='confWins',
        ),
        migrations.RenameField(
            model_name='nflteam',
            old_name='div_wins',
            new_name='divWins',
        ),
        migrations.RenameField(
            model_name='nflteam',
            old_name='tot_wins',
            new_name='totWins',
        ),
        migrations.RenameField(
            model_name='projection',
            old_name='current_week',
            new_name='currWeek',
        ),
        migrations.RenameField(
            model_name='projection',
            old_name='first_quartile',
            new_name='firstquartile',
        ),
        migrations.RenameField(
            model_name='projection',
            old_name='is_custom',
            new_name='isCustom',
        ),
        migrations.RenameField(
            model_name='projection',
            old_name='made_playoffs',
            new_name='madePlayoffs',
        ),
        migrations.RenameField(
            model_name='projection',
            old_name='standard_deviation',
            new_name='stdv',
        ),
        migrations.RenameField(
            model_name='projection',
            old_name='third_quartile',
            new_name='thirdquartile',
        ),
        migrations.RenameField(
            model_name='projection',
            old_name='won_conference',
            new_name='wonConference',
        ),
        migrations.RenameField(
            model_name='projection',
            old_name='won_division',
            new_name='wonDivision',
        ),
        migrations.RenameField(
            model_name='projection',
            old_name='won_super_bowl',
            new_name='wonSuperBowl',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='playoff_round',
            new_name='playoffRound',
        ),
        migrations.RenameField(
            model_name='upcominggames',
            old_name='away_score',
            new_name='awayScore',
        ),
        migrations.RenameField(
            model_name='upcominggames',
            old_name='away_team',
            new_name='awayTeam',
        ),
        migrations.RenameField(
            model_name='upcominggames',
            old_name='home_score',
            new_name='homeScore',
        ),
        migrations.RenameField(
            model_name='upcominggames',
            old_name='home_team',
            new_name='homeTeam',
        ),
        migrations.RenameField(
            model_name='upcominggames',
            old_name='is_complete',
            new_name='isComplete',
        ),
        migrations.RenameField(
            model_name='upcominggames',
            old_name='is_neutral',
            new_name='isNeutral',
        ),
        migrations.RemoveField(
            model_name='upcominggames',
            name='user_predictions',
        ),
        migrations.AddField(
            model_name='upcominggames',
            name='isCustom',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='upcominggames',
            name='isPicked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='upcominggames',
            name='teamPicked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.nflteam'),
        ),
        migrations.AddField(
            model_name='upcominggames',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GamePrediction',
        ),
    ]
