# Generated by Django 3.2.6 on 2024-08-01 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_auto_20240729_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('', 'No Prediction')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quarterback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qbr', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Quarterbacks',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='long',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='nflteam',
            old_name='confWins',
            new_name='conf_wins',
        ),
        migrations.RenameField(
            model_name='nflteam',
            old_name='divWins',
            new_name='div_wins',
        ),
        migrations.RenameField(
            model_name='nflteam',
            old_name='totWins',
            new_name='tot_wins',
        ),
        migrations.RenameField(
            model_name='projection',
            old_name='currWeek',
            new_name='current_week',
        ),
        migrations.RenameField(
            model_name='projection',
            old_name='firstquartile',
            new_name='first_quartile',
        ),
        migrations.RenameField(
            model_name='projection',
            old_name='isCustom',
            new_name='is_custom',
        ),
        migrations.RenameField(
            model_name='projection',
            old_name='madePlayoffs',
            new_name='made_playoffs',
        ),
        migrations.RenameField(
            model_name='projection',
            old_name='stdv',
            new_name='standard_deviation',
        ),
        migrations.RenameField(
            model_name='projection',
            old_name='thirdquartile',
            new_name='third_quartile',
        ),
        migrations.RenameField(
            model_name='projection',
            old_name='wonConference',
            new_name='won_conference',
        ),
        migrations.RenameField(
            model_name='projection',
            old_name='wonDivision',
            new_name='won_division',
        ),
        migrations.RenameField(
            model_name='projection',
            old_name='wonSuperBowl',
            new_name='won_super_bowl',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='playoffRound',
            new_name='playoff_round',
        ),
        migrations.RenameField(
            model_name='upcominggames',
            old_name='awayScore',
            new_name='away_score',
        ),
        migrations.RenameField(
            model_name='upcominggames',
            old_name='awayTeam',
            new_name='away_team',
        ),
        migrations.RenameField(
            model_name='upcominggames',
            old_name='homeScore',
            new_name='home_score',
        ),
        migrations.RenameField(
            model_name='upcominggames',
            old_name='homeTeam',
            new_name='home_team',
        ),
        migrations.RenameField(
            model_name='upcominggames',
            old_name='isComplete',
            new_name='is_complete',
        ),
        migrations.RenameField(
            model_name='upcominggames',
            old_name='isNeutral',
            new_name='is_neutral',
        ),
        migrations.RemoveField(
            model_name='upcominggames',
            name='isCustom',
        ),
        migrations.RemoveField(
            model_name='upcominggames',
            name='isPicked',
        ),
        migrations.RemoveField(
            model_name='upcominggames',
            name='teamPicked',
        ),
        migrations.RemoveField(
            model_name='upcominggames',
            name='user',
        ),
        migrations.AddField(
            model_name='gameprediction',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.upcominggames'),
        ),
        migrations.AddField(
            model_name='gameprediction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='upcominggames',
            name='user_predictions',
            field=models.ManyToManyField(through='main.GamePrediction', to=settings.AUTH_USER_MODEL),
        ),
    ]
