# Generated by Django 3.2.6 on 2024-08-01 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_auto_20240731_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcominggames',
            name='user_predictions',
        ),
        migrations.AddField(
            model_name='upcominggames',
            name='is_custom',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='upcominggames',
            name='is_picked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='upcominggames',
            name='team_picked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.nflteam'),
        ),
        migrations.AddField(
            model_name='upcominggames',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GamePrediction',
        ),
    ]
