# Generated by Django 3.2.6 on 2024-08-03 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20240731_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarterback',
            name='qbr',
        ),
        migrations.AlterField(
            model_name='quarterback',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='QuarterbackEloHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('elo_value', models.FloatField()),
                ('quarterback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_history', to='main.quarterback')),
            ],
            options={
                'unique_together': {('quarterback', 'date')},
            },
        ),
    ]
